"""empty message

Revision ID: 3c7d9f6518e1
Revises: 
Create Date: 2021-09-05 16:06:17.401091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7d9f6518e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('meme_types')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meme_types', sa.VARCHAR(length=512), nullable=True))

    # ### end Alembic commands ###
