"""empty message

Revision ID: d4ada8140cdc
Revises: dc03bafcb71b
Create Date: 2021-09-04 18:27:05.808555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ada8140cdc'
down_revision = 'dc03bafcb71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('meme_1', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('meme_2', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('meme_3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'meme_3')
    op.drop_column('user', 'meme_2')
    op.drop_column('user', 'meme_1')
    # ### end Alembic commands ###
